# This file lists tools managed by Rokit, a toolchain manager for Roblox projects.
# For more information, see https://github.com/rojo-rbx/rokit

# New tools can be added by running `rokit add <tool>` in a terminal.

[tools]
lune = "lune-org/lune@0.9.4"
lute = "luau-lang/lute@0.1.0-nightly.20250617"
stylua = "JohnnyMorganz/stylua@2.1.0"
